#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("feed_fetcher", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/feed_fetcher.rb", config.to_hash